### ISSUE TITLE
main example outputs 'panic: runtime error: slice bounds out of range [60:55]'

### ISSUE THREAD

**Issue by tronch0** [ava-labs/avalanche-network-runner#53]
I cloned avalance-network-runner, ran the tests, everything ok, but when I try to run the example main I get the error: 

> panic: runtime error: slice bounds out of range [60:55]

Here is the full transcript:
```

dev/avalanche-network-runner git:(main) ▶ go run examples/local/main.go
panic: runtime error: slice bounds out of range [60:55]

goroutine 1 [running]:
github.com/ava-labs/avalanchego/utils/logging.(*Log).format(0xc0029000e0, 0x1, {0xffa0e1, 0x1e}, {0xc000e154a0, 0x1, 0x1})
	/home/x1/go/pkg/mod/github.com/ava-labs/avalanchego@v1.7.1/utils/logging/log.go:197 +0x3a5
github.com/ava-labs/avalanchego/utils/logging.(*Log).log(0xc0029000e0, 0x4, {0xffa0e1, 0x1e}, {0xc000e154a0, 0xe49400, 0x1})
	/home/x1/go/pkg/mod/github.com/ava-labs/avalanchego@v1.7.1/utils/logging/log.go:172 +0x1c5
github.com/ava-labs/avalanchego/utils/logging.(*Log).Info(0xc000c1f8a8, {0xffa0e1, 0xe43360}, {0xc000e154a0, 0xc000c1f628, 0x4d75c5})
	/home/x1/go/pkg/mod/github.com/ava-labs/avalanchego@v1.7.1/utils/logging/log.go:224 +0x37
github.com/ava-labs/avalanche-network-runner/local.newNetwork({0x165a468, 0xc0029000e0}, {{0x0, 0x0}, {0xc002946000, 0xc07, 0xc80}, {0xc0021cf340, 0x5, 0x5}, ...}, ...)
	/home/x1/dev/avalanche-network-runner/local/network.go:171 +0x153
github.com/ava-labs/avalanche-network-runner/local.newDefaultNetwork({0x165a468, 0xc0029000e0}, {0xc0021c5500, 0x36}, 0x0, 0xc000e1ce08)
	/home/x1/dev/avalanche-network-runner/local/network.go:253 +0x1e5
github.com/ava-labs/avalanche-network-runner/local.NewDefaultNetwork(...)
	/home/x1/dev/avalanche-network-runner/local/network.go:235
main.run({0x165a468, 0xc0029000e0}, {0xc0021c5500, 0x36})
	/home/x1/dev/avalanche-network-runner/examples/local/main.go:74 +0x6f
main.main()
	/home/x1/dev/avalanche-network-runner/examples/local/main.go:67 +0x2a6
exit status 2
↑1 dev/avalanche-network-runner git:(main) ▶ go test ./...                
?   	github.com/ava-labs/avalanche-network-runner/api	[no test files]
?   	github.com/ava-labs/avalanche-network-runner/api/mocks	[no test files]
?   	github.com/ava-labs/avalanche-network-runner/examples/k8s	[no test files]
?   	github.com/ava-labs/avalanche-network-runner/examples/local	[no test files]
ok  	github.com/ava-labs/avalanche-network-runner/k8s	51.971s
?   	github.com/ava-labs/avalanche-network-runner/k8s/mocks	[no test files]
ok  	github.com/ava-labs/avalanche-network-runner/local	56.793s
?   	github.com/ava-labs/avalanche-network-runner/local/mocks	[no test files]
?   	github.com/ava-labs/avalanche-network-runner/network	[no test files]
?   	github.com/ava-labs/avalanche-network-runner/network/node	[no test files]
ok  	github.com/ava-labs/avalanche-network-runner/utils	(cached)
Ξ dev/avalanche-network-runner git:(main) ▶ go version 
go version go1.17.2 linux/amd64
Ξ dev/avalanche-network-runner git:(main) ▶ git pull
Already up to date.
Ξ dev/avalanche-network-runner git:(main) ▶ 

```

Im running on ubuntu 20.04.

**Comment by danlaine** [comment]
@tronch0 

Sorry about that, and thanks for reporting. There was an issue in the version of AvalancheGo that this program uses as a dependency. I've just updated the dependency, so pulling `main` should resolve the issue. Please re-open this issue if it doesn't.
